# -*- coding: utf-8 -*-
"""Actividad3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vc_y2TylquxqRS9SInhx-QFTG85gVbP3

*Con estos datos que ya tienes agrega una nueva columna para que puedas predecir, en esa columna ahora vas a tener el país del programador. Ojo, recuerda que la regresión lineal simple solo trabaja con datos continuos, así que cada país deberás represarlo con un número, por ejemplo Ecuador = 1, España = 2.*
"""

import pandas as pd

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

dataset = pd.read_csv('/content/salarios.csv')
dataset.head (5)

dataset['pais'] = np.random.randint(1, 7, dataset.shape[0])
for i in dataset.index:
  if dataset['Salario'][i] >=1000 and dataset['Salario'][i]<2500:
    dataset['pais'][i]=1
  elif dataset['Salario'][i]>=2500 and dataset['Salario'][i]<3000:
    dataset['Salario'][i]=2
  else:
    dataset['pais'][i]=3
dataset.head(25)

x=dataset.iloc[:, 2:3].values
y=dataset.iloc[:, 1].values
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.2, random_state=0)
X_train

regresion=LinearRegression()
regresion.fit(X_train, Y_train)
vision_train=plt
vision_train.scatter(X_train, Y_train, color='blue')
vision_train.plot(X_train, regresion.predict(X_train),color='black')
vision_train.title('Salario & Pais')
vision_train.xlabel('Pais')
vision_train.ylabel('Salario')
vision_train.show

vision_train=plt
vision_train.scatter(X_test, Y_test, color='red')
vision_train.plot(X_train, regresion.predict(X_train),color='black')
vision_train.title('Salario & Pais')
vision_train.xlabel('Pais')
vision_train.ylabel('Salario')
vision_train.show