# -*- coding: utf-8 -*-
"""Actividad1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BFb5lY_ZvMzmVCMxKUGD4AUIjMj_meoJ

Actividad 1
•	Crear un arreglo de 4 dimensiones ordenados por la edad o el nombre
"""

import numpy as np
key=[('Nombre','S10'),('Apellido','S10'),('Edad',int)]
datos=[('Juan','Alonso',19),('Byron','Pilligua',24),('Carlos','Reyes',17),('Marcos','Anchundia',20)]
arr= np.array(datos, dtype=key)
print(arr)

print("Ordenar por nombre")
np.sort(arr,order='Nombre')

print("Ordenar por edad")
np.sort(arr,order='Edad')